# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, E, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser --profile-directory="Default"
bindd = SUPER SHIFT, J, Browser, exec, $browser --profile-directory="Profile 1"
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private --profile-directory="Default"
# bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-webapp "https://music.youtube.com/" --profile-directory="Default"
bindd = SUPER SHIFT, M, Music, exec, $terminal mutui
bindd = SUPER SHIFT, N, Neovim, exec, $terminal nvim
bindd = SUPER SHIFT, V, Editor, exec, code
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-tui lazygit
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com" --profile-directory="Default"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
#bindd = SUPER SHIFT, C, OpenCode, exec, $terminal opencode
bindd = SUPER SHIFT, C, CCTV, exec, cctv-viewer
#bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/" --profile-directory="Default"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/" --profile-directory="Default"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/" --profile-directory="Default"
bindd = SUPER SHIFT, X, X, exec, hyprpicker -a
bindd = SUPER SHIFT, L, Lock Screen, exec, omarchy-lock-screen
bindd = SUPER SHIFT, H, Homelab Dashboard, exec, omarchy-launch-webapp "http://192.168.1.19:7575/boards/Dashboard" --profile-directory="Default"

bind = SUPER, F9, exec, pactl set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-speaker && pactl set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-speaker; sleep 0.1; notify-send "Audio   Speakers";
bind = SUPER, F10, exec, pactl set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-headphones && pactl set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-headphones; sleep 0.1; notify-send "Audio   Headphones";

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
